//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    public class MQueryCalibrationStateResponse : Message
    {
        public const string RosMessageName = "control_msgs/QueryCalibrationState";

        public bool is_calibrated;

        public MQueryCalibrationStateResponse()
        {
            this.is_calibrated = false;
        }

        public MQueryCalibrationStateResponse(bool is_calibrated)
        {
            this.is_calibrated = is_calibrated;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.is_calibrated));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.is_calibrated = BitConverter.ToBoolean(data, offset);
            offset += 1;

            return offset;
        }

        public override string ToString()
        {
            return "MQueryCalibrationStateResponse: " +
            "\nis_calibrated: " + is_calibrated.ToString();
        }
    }
}
