//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Moveit
{
    public class MCartesianTrajectoryPoint : Message
    {
        public const string RosMessageName = "moveit_msgs/CartesianTrajectoryPoint";

        //  The definition of a cartesian point in a trajectory. Defines the cartesian state of the point and it's time,
        //  following the pattern of the JointTrajectory message
        public MCartesianPoint point;
        public MDuration time_from_start;

        public MCartesianTrajectoryPoint()
        {
            this.point = new MCartesianPoint();
            this.time_from_start = new MDuration();
        }

        public MCartesianTrajectoryPoint(MCartesianPoint point, MDuration time_from_start)
        {
            this.point = point;
            this.time_from_start = time_from_start;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(point.SerializationStatements());
            listOfSerializations.AddRange(time_from_start.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.point.Deserialize(data, offset);
            offset = this.time_from_start.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "MCartesianTrajectoryPoint: " +
            "\npoint: " + point.ToString() +
            "\ntime_from_start: " + time_from_start.ToString();
        }
    }
}
