//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class MCartesianPoint : Message
    {
        public const string RosMessageName = "moveit_msgs/CartesianPoint";

        //  This message defines a point in a cartesian trajectory
        public Geometry.MPose pose;
        public Geometry.MTwist velocity;
        public Geometry.MAccel acceleration;

        public MCartesianPoint()
        {
            this.pose = new Geometry.MPose();
            this.velocity = new Geometry.MTwist();
            this.acceleration = new Geometry.MAccel();
        }

        public MCartesianPoint(Geometry.MPose pose, Geometry.MTwist velocity, Geometry.MAccel acceleration)
        {
            this.pose = pose;
            this.velocity = velocity;
            this.acceleration = acceleration;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(pose.SerializationStatements());
            listOfSerializations.AddRange(velocity.SerializationStatements());
            listOfSerializations.AddRange(acceleration.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.pose.Deserialize(data, offset);
            offset = this.velocity.Deserialize(data, offset);
            offset = this.acceleration.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "MCartesianPoint: " +
            "\npose: " + pose.ToString() +
            "\nvelocity: " + velocity.ToString() +
            "\nacceleration: " + acceleration.ToString();
        }
    }
}
