//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Moveit
{
    public class MGenericTrajectory : Message
    {
        public const string RosMessageName = "moveit_msgs/GenericTrajectory";

        //  A generic trajectory message that may either encode a joint- or cartesian-space trajectory, or both
        //  Trajectories encoded in this message are considered semantically equivalent
        public MHeader header;
        public Trajectory.MJointTrajectory[] joint_trajectory;
        public MCartesianTrajectory[] cartesian_trajectory;

        public MGenericTrajectory()
        {
            this.header = new MHeader();
            this.joint_trajectory = new Trajectory.MJointTrajectory[0];
            this.cartesian_trajectory = new MCartesianTrajectory[0];
        }

        public MGenericTrajectory(MHeader header, Trajectory.MJointTrajectory[] joint_trajectory, MCartesianTrajectory[] cartesian_trajectory)
        {
            this.header = header;
            this.joint_trajectory = joint_trajectory;
            this.cartesian_trajectory = cartesian_trajectory;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(header.SerializationStatements());
            
            listOfSerializations.Add(BitConverter.GetBytes(joint_trajectory.Length));
            foreach(var entry in joint_trajectory)
                listOfSerializations.Add(entry.Serialize());
            
            listOfSerializations.Add(BitConverter.GetBytes(cartesian_trajectory.Length));
            foreach(var entry in cartesian_trajectory)
                listOfSerializations.Add(entry.Serialize());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.header.Deserialize(data, offset);
            
            var joint_trajectoryArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.joint_trajectory= new Trajectory.MJointTrajectory[joint_trajectoryArrayLength];
            for(var i = 0; i < joint_trajectoryArrayLength; i++)
            {
                this.joint_trajectory[i] = new Trajectory.MJointTrajectory();
                offset = this.joint_trajectory[i].Deserialize(data, offset);
            }
            
            var cartesian_trajectoryArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.cartesian_trajectory= new MCartesianTrajectory[cartesian_trajectoryArrayLength];
            for(var i = 0; i < cartesian_trajectoryArrayLength; i++)
            {
                this.cartesian_trajectory[i] = new MCartesianTrajectory();
                offset = this.cartesian_trajectory[i].Deserialize(data, offset);
            }

            return offset;
        }

        public override string ToString()
        {
            return "MGenericTrajectory: " +
            "\nheader: " + header.ToString() +
            "\njoint_trajectory: " + System.String.Join(", ", joint_trajectory.ToList()) +
            "\ncartesian_trajectory: " + System.String.Join(", ", cartesian_trajectory.ToList());
        }
    }
}
