//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UrMoveit
{
    public class MUR_Q : Message
    {
        public const string RosMessageName = "ur_moveit/UR_Q";

        public double[] joint;

        public MUR_Q()
        {
            this.joint = new double[0];
        }

        public MUR_Q(double[] joint)
        {
            this.joint = joint;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            
            listOfSerializations.Add(BitConverter.GetBytes(joint.Length));
            foreach(var entry in joint)
                listOfSerializations.Add(BitConverter.GetBytes(entry));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            
            var jointArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.joint= new double[jointArrayLength];
            for(var i = 0; i < jointArrayLength; i++)
            {
                this.joint[i] = BitConverter.ToDouble(data, offset);
                offset += 8;
            }

            return offset;
        }

        public override string ToString()
        {
            return "MUR_Q: " +
            "\njoint: " + System.String.Join(", ", joint.ToList());
        }
    }
}
