//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    public class MGripperCommandGoal : Message
    {
        public const string RosMessageName = "control_msgs/GripperCommand";

        public MGripperCommand command;

        public MGripperCommandGoal()
        {
            this.command = new MGripperCommand();
        }

        public MGripperCommandGoal(MGripperCommand command)
        {
            this.command = command;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(command.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.command.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "MGripperCommandGoal: " +
            "\ncommand: " + command.ToString();
        }
    }
}
