//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Control
{
    public class MPointHeadGoal : Message
    {
        public const string RosMessageName = "control_msgs/PointHead";

        public Geometry.MPointStamped target;
        public Geometry.MVector3 pointing_axis;
        public string pointing_frame;
        public MDuration min_duration;
        public double max_velocity;

        public MPointHeadGoal()
        {
            this.target = new Geometry.MPointStamped();
            this.pointing_axis = new Geometry.MVector3();
            this.pointing_frame = "";
            this.min_duration = new MDuration();
            this.max_velocity = 0.0;
        }

        public MPointHeadGoal(Geometry.MPointStamped target, Geometry.MVector3 pointing_axis, string pointing_frame, MDuration min_duration, double max_velocity)
        {
            this.target = target;
            this.pointing_axis = pointing_axis;
            this.pointing_frame = pointing_frame;
            this.min_duration = min_duration;
            this.max_velocity = max_velocity;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(target.SerializationStatements());
            listOfSerializations.AddRange(pointing_axis.SerializationStatements());
            listOfSerializations.Add(SerializeString(this.pointing_frame));
            listOfSerializations.AddRange(min_duration.SerializationStatements());
            listOfSerializations.Add(BitConverter.GetBytes(this.max_velocity));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.target.Deserialize(data, offset);
            offset = this.pointing_axis.Deserialize(data, offset);
            var pointing_frameStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.pointing_frame = DeserializeString(data, offset, pointing_frameStringBytesLength);
            offset += pointing_frameStringBytesLength;
            offset = this.min_duration.Deserialize(data, offset);
            this.max_velocity = BitConverter.ToDouble(data, offset);
            offset += 8;

            return offset;
        }

        public override string ToString()
        {
            return "MPointHeadGoal: " +
            "\ntarget: " + target.ToString() +
            "\npointing_axis: " + pointing_axis.ToString() +
            "\npointing_frame: " + pointing_frame.ToString() +
            "\nmin_duration: " + min_duration.ToString() +
            "\nmax_velocity: " + max_velocity.ToString();
        }
    }
}
