//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    public class MPointHeadFeedback : Message
    {
        public const string RosMessageName = "control_msgs/PointHead";

        public double pointing_angle_error;

        public MPointHeadFeedback()
        {
            this.pointing_angle_error = 0.0;
        }

        public MPointHeadFeedback(double pointing_angle_error)
        {
            this.pointing_angle_error = pointing_angle_error;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.pointing_angle_error));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.pointing_angle_error = BitConverter.ToDouble(data, offset);
            offset += 8;

            return offset;
        }

        public override string ToString()
        {
            return "MPointHeadFeedback: " +
            "\npointing_angle_error: " + pointing_angle_error.ToString();
        }
    }
}
