//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Control
{
    public class MSingleJointPositionGoal : Message
    {
        public const string RosMessageName = "control_msgs/SingleJointPosition";

        public double position;
        public MDuration min_duration;
        public double max_velocity;

        public MSingleJointPositionGoal()
        {
            this.position = 0.0;
            this.min_duration = new MDuration();
            this.max_velocity = 0.0;
        }

        public MSingleJointPositionGoal(double position, MDuration min_duration, double max_velocity)
        {
            this.position = position;
            this.min_duration = min_duration;
            this.max_velocity = max_velocity;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.position));
            listOfSerializations.AddRange(min_duration.SerializationStatements());
            listOfSerializations.Add(BitConverter.GetBytes(this.max_velocity));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.position = BitConverter.ToDouble(data, offset);
            offset += 8;
            offset = this.min_duration.Deserialize(data, offset);
            this.max_velocity = BitConverter.ToDouble(data, offset);
            offset += 8;

            return offset;
        }

        public override string ToString()
        {
            return "MSingleJointPositionGoal: " +
            "\nposition: " + position.ToString() +
            "\nmin_duration: " + min_duration.ToString() +
            "\nmax_velocity: " + max_velocity.ToString();
        }
    }
}
